apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy-proxy
  namespace: grpc-lb
spec:
  selector:
    matchLabels:
      app: envoy-proxy
  template:
    metadata:
      labels:
        app: envoy-proxy
    spec:
      containers:
        - name: envoy-proxy
          image: envoyproxy/envoy:v1.30.3
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "64Mi"
              cpu: "100m"
          ports:
            - containerPort: 80
          command: ["envoy"]
          args: ["-c", "/etc/envoy.yaml"]
          volumeMounts:
            - name: config
              mountPath: /etc/envoy.yaml
              subPath: envoy.yaml
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: config
          configMap:
            name: "envoy-proxy-config"
